version: '3.7'

services:
  # Run local DB
  web_mitra_paylsa:
    image: fandu139/web-mitra-paylsa:1.0.1
    ports:
      - '8080:3000'
    restart: unless-stopped

  service_web_mitra_paylsa:
    image: fandu139/transaction-svc-paylsa:1.1.0
    # ports:
      # - '3001:3000'
    restart: unless-stopped
    environment:
      - MIDTRANS_IS_PRODUCTION=true
      - MIDTRANS_SERVER_KEY=Mid-server-H-r_eWjmw2sYohmc6B4JhHqb
      - MIDTRANS_CLIENT_KEY=Mid-client-ctnfcJxDPlbJpQtE
      - EMAIL_CLIENT=fandupratamasvc@gmail.com
      - CREDENTIALS_CLIENT=123456
      - ROLE_CLIENT=Service
      # - MIDTRANS_SERVER_KEY=SB-Mid-server-B4FtSi59HABjLKrJ1ZcVQWII
      # - MIDTRANS_CLIENT_KEY=SB-Mid-client-ezeO00KzWvGTFs2H
      # - EMAIL_CLIENT=fandupratamasvc@gmail.com
      # - CREDENTIALS_CLIENT=123456
      # - ROLE_CLIENT=Service
      - PORT=3001

  prometheus:
    image: prom/prometheus
    # ports:
    #  - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  node-exporter:
    image: prom/node-exporter
    # ports:
    #  - "9100:9100"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning

  kong-database:
    image: postgres:13
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kong
      - POSTGRES_DB=kong
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  kong-migrations:
    image: kong
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PASSWORD=kong
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
    command: kong migrations bootstrap
    restart: on-failure
    depends_on:
      - kong-database

  kong:
    image: kong
    container_name: kong
    environment:
      - LC_CTYPE=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    restart: on-failure
    volumes:
      - ./kong.yml:/etc/kong/kong.yml
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"
    links:
      - kong-database:kong-database
    depends_on:
      - kong-migrations

  konga:
    image: pantsel/konga
    volumes:
      - ./konga_data:/path/to/data
    ports:
      - 1337:1337
    links:
      - kong:kong
    container_name: konga
    environment:
      - NODE_ENV=production

  webserver:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./configNginxWebMitra:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - kong

networks:
  default:
    name: monitoring-api-network

