version: '3.7'

services:
  # Run local DB
  service_web_mitra_paylsa:
    image: fandu139/web-mitra-paylsa:1.0.1
    ports:
      - '8080:3000'
    restart: unless-stopped
    environment:
      - MIDTRANS_SERVER_KEY=SB-Mid-server-B4FtSi59HABjLKrJ1ZcVQWII
      - MIDTRANS_CLIENT_KEY=SB-Mid-client-ezeO00KzWvGTFs2H
      - EMAIL_CLIENT=fandupratamasvc@gmail.com
      - CREDENTIALS_CLIENT=123456
      - ROLE_CLIENT=Service
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring

  kong-database:
    image: postgres:13
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kong
      - POSTGRES_DB=kong
    volumes:
      - ./dataPostgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - monitoring

  kong:
    image: kong
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PG_DATABASE=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_USER=root
    depends_on:
      - kong-database
    volumes:
      - ./kong.yml:/etc/kong/kong.yml
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"
    networks:
      - monitoring

networks:
  monitoring:

